# Site settings
title: mogulla3
tag_text: mogulla3
description: description

# Build settings
markdown: kramdown
exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
